cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('',
         views.cart_detail,
         name='cart_detail'),
    path('add/<int:dish_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:dish_id>/',
         views.cart_remove,
         name='cart_remove'),
    path('clear/',
         views.cart_clear,
         name='cart_clear'),
    path('add_random_food/',
         views.cart_add_random_food,
         name='cart_add_random_food'),
    path('add_random_drink/',
         views.cart_add_random_drink,
         name='cart_add_random_drink'),
    path('update_plus/<int:dish_id>/',
         views.cart_update_plus,
         name='cart_update_plus'),
    path('update_minus/<int:dish_id>/',
         views.cart_update_minus,
         name='cart_update_minus'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/',
         views.order_create,
         name='order_create',),
    path('history/',
         views.get_orders_history,
         name='orders_history'),
    path('<int:order_id>/pdf/',
         views.order_pdf,
         name='order_pdf'),
]

site_food_order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('food_order.urls', namespace='food_order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddDishForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.NumberInput(attrs={'style': 'width:7ch',
                                        'value': 1,
                                        'min': 1,
                                        'max': 20,
                                        'step': 1}),
        required=False,
        initial=1,
        label="")
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)


class CartUpdateQuantityDish(forms.Form):
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from food_order.models import Dish
from .cart import Cart
from .forms import CartAddDishForm, CartUpdateQuantityDish
from django.contrib import messages

from random import choice


@require_POST
def cart_add(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    form = CartAddDishForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        quantity = cd['quantity']
        messages.success(request, f'Товар - "{dish}" ({quantity} шт.) добавлен в корзину')
        cart.add(dish=dish,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    else:
        messages.error(request, f'Ошибка \n Товар - {dish} не добавлен')
    return redirect('food_order:dish_list')


@require_POST
def cart_remove(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.remove(dish)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request,
                  'cart/detail.html',
                  {'cart': cart})


def cart_update_plus(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    form = CartUpdateQuantityDish(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(dish=dish,
                 quantity=1,
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_update_minus(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    form = CartUpdateQuantityDish(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.remove(dish=dish,
                    quantity=1,
                    override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


@require_POST
def cart_add_random_food(request):
    cart = Cart(request)
    eda = [dish for dish in list(Dish.objects.all().values())
           if dish['category_id'] != 5]
    dish_rand = choice(eda)
    dish = get_object_or_404(Dish, id=dish_rand['id'])
    form = CartAddDishForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(dish=dish,
                 quantity=1,
                 override_quantity=cd['override'])
        messages.success(request, f'Товар - "{dish}" добавлен в корзину')
    else:
        messages.error(request, f'Ошибка \n Товар - {dish} не добавлен')
    return redirect('food_order:dish_list')


@require_POST
def cart_add_random_drink(request):
    cart = Cart(request)
    eda = [dish for dish in list(Dish.objects.all().values())
           if dish['category_id'] == 5]
    dish_rand = choice(eda)
    dish = get_object_or_404(Dish, id=dish_rand['id'])
    form = CartAddDishForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(dish=dish,
                 quantity=1,
                 override_quantity=cd['override'])
        messages.success(request, f'Товар - "{dish}" добавлен в корзину')
    else:
        messages.error(request, f'Ошибка \n Товар - {dish} не добавлен')
    return redirect('food_order:dish_list')

cart/templates/cart/detail.html
{% extends "food_order/base.html" %}
{% load static %}

{% block page_header %}
  <div class="text-center"><h1 class="display-3">Корзина <span class="badge badge-secondary badge-pill">{{ cart.len }}</span></h1></div>
{% endblock %}

{% block content %}
  {% if cart %}
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-1 g-3">

      {% for item in cart %}
        {% with dish=item.dish %}
          <div class="col-md-12 col-sm-12 col-md-offset-1">
            <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-3 col-sm-5">
                      <a href="{{ dish.get_absolute_url }}">
                          <img class="card-img-top w-30 h-40"
                              src="{% if dish.image %}{{ dish.image.url }}
                                    {% else %}{% static 'img/no_image.png' %}{% endif %}"
                              alt="">
                      </a>
                    </div>
                    <div class="col-md-9 col-sm-7">
                      <a href="{{ dish.get_absolute_url }}"><h5
                              class="card-title">{{ dish.name }}</h5></a>

                      <p class="card-text">{{ dish.description }}</p>
                    </div>
                  </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-sm-4 col-md-4">
                                <a href="{% url 'cart:cart_update_plus' dish.id %}"
                                  class="btn btn-outline-dark btn-sm">&plus;</a>
                                {{ item.quantity }}
                                <a href="{% url 'cart:cart_update_minus' dish.id %}"
                                  class="btn btn-outline-dark btn-sm">&minus;</a>
                            </div>
                            <div class="col-sm-4 col-md-4">Цена за штуку: {{ item.price }} руб.</div>
                            <div class="col-sm-4 col-md-4">

                            </div>
                        </div>
                    </li>
                </ul>
            </div>
          </div>
        {% endwith %}
      {% endfor %}
    </div>
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2" >
      <div class="col-sm-4 col-md-8"></div>
      <div class="col-sm-4 col-md-2">
        <h4  class="float-right">Итого:</h4 >
      </div>
      <div class="col-sm-4 col-md-2">
        <h4 class="float-right">{{ cart.get_total_price}} руб.</h4>
      </div>

    </div>
    <div class="row">
      <div class="col-sm-3 col-md-7"></div>
      <div class="col-sm-4 col-md-2">
        <a class="btn btn-danger btn-lg float-right" href="{% url 'cart:cart_clear' %}">
          Очистить корзину
        </a>
        {% if user.is_authenticated %}
          </div>
          <div class="col-sm-1 col-md-1"></div>
          <div class="col-sm-4 col-md-2">
            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
                Перейти к заказу
            </a>
          </div>
        {% else %}
          </div>
          <div class="col-sm-1 col-md-1"></div>
          <div class="col-sm-4 col-md-2">
            <a class="btn btn-success btn-lg float-right" href="{% url 'users:login' %}">
                Перейти к заказу
            </a>
          </div>
        {% endif %}
    </div>
  </div>
  {% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
  {% endif %}
{% endblock %}