cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('',
         views.cart_detail,
         name='cart_detail'),
    path('add/<int:dish_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:dish_id>/',
         views.cart_remove,
         name='cart_remove'),
    path('clear/',
         views.cart_clear,
         name='cart_clear'),
    path('add_random_food/',
         views.cart_add_random_food,
         name='cart_add_random_food'),
    path('add_random_drink/',
         views.cart_add_random_drink,
         name='cart_add_random_drink'),
    path('update_plus/<int:dish_id>/',
         views.cart_update_plus,
         name='cart_update_plus'),
    path('update_minus/<int:dish_id>/',
         views.cart_update_minus,
         name='cart_update_minus'),
]

food_order/urls.py
from django.urls import path
from . import views


app_name = 'food_order'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('dishes',
         views.dish_list,
         name='dish_list'),
    path('<slug:category_slug>/',
         views.dish_list,
         name='dish_list_by_category'),
    path('<int:id>/<slug:slug>/',
         views.dish_detail,
         name='dish_detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/',
         views.order_create,
         name='order_create',),
    path('history/',
         views.get_orders_history,
         name='orders_history'),
    path('<int:order_id>/pdf/',
         views.order_pdf,
         name='order_pdf'),
]

site_food_order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('food_order.urls', namespace='food_order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

food_order/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """ Модель категорий меню """

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food_order:dish_list_by_category',
                       args=[self.slug])


class Dish(models.Model):
    """ Модель блюда """

    category = models.ForeignKey(Category,
                                 related_name='dishes',
                                 on_delete=models.CASCADE,
                                 default=None)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50,
                            unique=True)
    image = models.ImageField(upload_to='dishes/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    composition = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food_order:dish_detail',
                       args=[self.id, self.slug])

food_order/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Dish
from cart.forms import CartAddDishForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    """Домашняя страница сервиса"""
    return render(request, 'food_order/index.html')


def dish_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    dishes_list = Dish.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        dishes_list = dishes_list.filter(category=category)
    paginator = Paginator(dishes_list, 6)
    page_number = request.GET.get('page', 1)
    try:
        dishes = paginator.page(page_number)
    except PageNotAnInteger:
        dishes = paginator.page(1)
    except EmptyPage:
        dishes = paginator.page(paginator.num_pages)
    cart_dish_form = CartAddDishForm()

    return render(request,
                  'food_order/dish/list.html',
                  {'category': category,
                   'categories': categories,
                   'dishes': dishes,
                   'cart_dish_form': cart_dish_form})


def dish_detail(request, id, slug):
    dish = get_object_or_404(Dish,
                             id=id,
                             slug=slug,
                             available=True)
    cart_dish_form = CartAddDishForm()
    return render(request,
                  'food_order/dish/detail.html',
                  {'dish': dish,
                   'cart_dish_form': cart_dish_form})

food_order/templates/food_order/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="/static/css/base.css">

    <title>Order food</title>

  </head>
  <body>
      <nav class="navbar navbar-expand-md navbar-light mb-4 border">
        {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'food_order:dish_list'%}">
              Order food</a>
        {% else %}
          <a class="navbar-brand" href="{% url 'food_order:index'%}">
              Order food</a>
        {% endif %}
        {% with total_items=cart|length %}
        {% if total_items > 0 %}
          <or class="nav-item d-block d-sm-block d-md-none ml-auto">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}">
              <i class="bi bi-basket btn btn-outline-primary mr-sm-2 mr-md-0 mt-md-0" href="{% url 'cart:cart_detail' %}">
                {{ cart.get_total_price }} руб.
              </i>
            </a>
          </or>
        {% endif %}
        {% endwith %}
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse ml-auto" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item my-2">
              <a class="nav-link" href="{% url 'food_order:dish_list' %}">
                <i class="bi bi-shop-window"></i> Меню</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item dropdown my-2">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="bi bi-person-circle mr-2 mt-2"></i>{{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item" href="{% url 'users:edit' %}">Мои данные</a>
                  <a class="dropdown-item" href="{% url 'orders:orders_history' %}">Мои заказы</a>
                  <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                </div>
              </li>
            {% else %}
              <li class="nav-item my-2">
                <a class="nav-link-inline btn btn-outline-primary mr-2 mt-md-0" href="{% url 'users:register' %}" role="button">Зарегистрироваться</a>
              </li>
              <li class="nav-item my-2">
                <a class="nav-link-inline btn btn-outline-primary mt-sm-1 mt-md-0" href="{% url 'users:login' %}" role="button">Войти</a>
              </li>
            {% endif %}
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
              <li class="nav-item d-none d-md-block ml-auto">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                  <i class="bi bi-basket btn btn-outline-primary mr-sm-2 mr-md-0 mt-md-0" href="{% url 'cart:cart_detail' %}">
                    {{ cart.get_total_price }} руб.
                  </i>
                </a>
              </li>
            {% endif %}
            {% endwith %}
            <li class="nav-item d-none d-md-block ml-auto">
              <a class="nav-link" href="{% url 'orders:orders_history' %}">
                <i class="bi bi-list-task btn btn-secondary mr-sm-2 mr-md-0 mt-md-0" href="{% url 'orders:orders_history' %}"></i>
              </a>
            </li>
          </ul>
        </div>
      </nav>
        <div class="container pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="container-fluid  mb-2 noborder" >
            {% block content %}{% endblock content %}
        </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>

</html>

food_order/templates/food_order/index.html
{% extends "food_order/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block page_header %}

    <div class="jumborton">
      <div class="text-center"><h1 class="display-3">Сервис для корпоративного заказа еды</h1></div>

      <p class="lead">Регистрируйся и заказывай любимую еду</p>


      {% if user.is_authenticated %}
         <a class="btn btn-lg btn-primary" href="{% url 'food_order:dish_list' %}"
            role="button">Закзать еду</a>
      {% else %}
         <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Зарегистрироваться</a>
         <a class="btn btn-lg btn-outline-primary" href="{% url 'users:login' %}"
            role="button">Войти</a>
      {% endif %}
    </div>

{% endblock page_header %}