cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('',
         views.cart_detail,
         name='cart_detail'),
    path('add/<int:dish_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:dish_id>/',
         views.cart_remove,
         name='cart_remove'),
    path('clear/',
         views.cart_clear,
         name='cart_clear'),
    path('add_random_food/',
         views.cart_add_random_food,
         name='cart_add_random_food'),
    path('add_random_drink/',
         views.cart_add_random_drink,
         name='cart_add_random_drink'),
    path('update_plus/<int:dish_id>/',
         views.cart_update_plus,
         name='cart_update_plus'),
    path('update_minus/<int:dish_id>/',
         views.cart_update_minus,
         name='cart_update_minus'),
]

food_order/urls.py
from django.urls import path
from . import views


app_name = 'food_order'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('dishes',
         views.dish_list,
         name='dish_list'),
    path('<slug:category_slug>/',
         views.dish_list,
         name='dish_list_by_category'),
    path('<int:id>/<slug:slug>/',
         views.dish_detail,
         name='dish_detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/',
         views.order_create,
         name='order_create',),
    path('history/',
         views.get_orders_history,
         name='orders_history'),
    path('<int:order_id>/pdf/',
         views.order_pdf,
         name='order_pdf'),
]

site_food_order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('food_order.urls', namespace='food_order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from food_order.models import Dish
from django.contrib.auth.models import User


class Order(models.Model):
    name = models.ForeignKey(User,
                             related_name='name_employee',
                             on_delete=models.CASCADE)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish,
                             related_name='order_items',
                             on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from django.contrib.auth.models import User
from users.models import Employee

from datetime import date


class OrderCreateForm(forms.ModelForm):
    name = forms.ModelChoiceField(queryset=User.objects.all(),
                                  label="Выберите имя",
                                  widget=forms.Select(
                                attrs={'class': 'form-control select mb-3'}))
    date = forms.DateField(widget=forms.DateInput(
                                format='%d-%m-%Y',
                                attrs={'type': 'date',
                                       'class': 'form-control mb-3'}),
                           required=True,
                           label="Выберите дату",
                           initial=date.today().strftime('%d-%m-%Y'))

    class Meta:
        model = Order
        fields = ['name', 'date']


class EmployeeCompanyForm(forms.ModelForm):
    company = forms.CharField(label='Название компании',
                              disabled=True)

    class Meta:
        model = Employee
        fields = ['company']

    def get_company(self):
        company_name = self.cleaned_data['company']
        return company_name

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Order, OrderItem
from food_order.models import Dish
from users.models import Employee
from cart.cart import Cart
from django.contrib.auth.models import User
from .forms import OrderCreateForm, EmployeeCompanyForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from .send import send_report
import weasyprint


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        company_form = EmployeeCompanyForm(instance=request.user.employee,
                                           data=request.POST)
        if form.is_valid() and company_form.is_valid():
            order = form.save()
            company_name = company_form.get_company()
            form.fields['name'].queryset = \
                User.objects.filter(employee__company=company_name)
            for item in cart:
                OrderItem.objects.create(order=order,
                                         dish=item['dish'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
        company_form = EmployeeCompanyForm(instance=request.user.employee,
                                           data=request.POST)
        if company_form.is_valid():
            company_name = company_form.get_company()
            form.fields['name'].queryset = \
                User.objects.filter(employee__company=company_name)
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart,
                   'form': form,
                   'company_form': company_form})


@login_required
def get_orders_history(request):

    client = list(User.objects.filter(id=request.user.id).values())
    orders_list = [order for order in list(Order.objects.all().values())
                   if order['name_id'] == client[0]['id']]
    orders_id = [id['id'] for id in orders_list]
    orders_item_sum = {}
    orders_items_dishes = {}

    for i in orders_id:
        orders_item_sum[i] = 0
        orders_items_dishes[i] = []

    for item in list(OrderItem.objects.all().values()):
        for i in list(orders_item_sum.keys()):
            if item['order_id'] == i:
                orders_item_sum[i] += item['price'] * item['quantity']
                for n in list(Dish.objects.filter(id=item['dish_id'])):
                    orders_items_dishes[i].append(n.name)

    for order in orders_list:
        if int(order['id']) in list(orders_item_sum.keys()):
            order['price'] = orders_item_sum[int(order['id'])]
            order['dishes'] = orders_items_dishes[int(order['id'])]

    paginator = Paginator(orders_list, 10)
    page_number = request.GET.get('page', 1)
    try:
        orders = paginator.page(page_number)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    return render(request,
                  'orders/order/history.html',
                  {'orders': orders})


@login_required
def order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(
                                                settings.STATIC_ROOT / 'css/pdf.css')])
    # send_report(request, order_id)
    # return redirect('orders:orders_history')
    return response

orders/templates/orders/order/create.html
{% extends "food_order/base.html" %}
{% load static %}
{{ form.media }}


{% block page_header %}
<div class="py-5 text-center">
  <div class="text-center"><h1>Оформление заказа</h1></div>
</div>
{% endblock %}

{% block content %}
<section>
  <div class="container">

      <div class="row g-5">
        <div class="col-md-5 col-lg-4 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Корзина</span>
          </h4>
          <ul class="list-group mb-3">
            {% for item in cart %}
              {% with dish=item.dish %}
                <li class="list-group-item d-flex justify-content-between lh-sm">
                <div>
                  <h6 class="my-0">{{ dish.name }}</h6>
                  <small class="text-muted">{{ item.quantity }} шт.</small>
                </div>
                  <span class="text-muted">{{ item.price }} руб.</span>
                  </li>
              {% endwith %}
            {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                  <span>Сумма к оплате</span>
                  <strong>{{ cart.get_total_price }} руб.</strong>
                </li>
          </ul>
        </div>
        <div class="col-md-7 col-lg-8">
          <h4 class="mb-3">Заполните данные:</h4>
          <form method="post" class="order-form">
            {{ company_form.as_p }}
            {{ form.as_p }}
            {% csrf_token %}
            <hr class="my-4">
            <button class="w-100 btn btn-primary btn-lg" type="submit">Заказать</button>
            <p><input type="hidden"></p>
          </form>
      </div>
    </div>
  </div>
</section> 
{% endblock %}

orders/templates/orders/order/created.html
{% extends "food_order/base.html" %}

{% block page_header %}
<div class="text-center">
  <div class="text-center"><h1>Спасибо за заказ</h1></div>
</div>
{% endblock %}

{% block content %}
<div class="text-center">
  <h3>
    <p>Ваш заказ оформлен. Номер вашего заказа -
    <strong>{{ order.id }}</strong>.</p>
  </h3>
</div>
{% endblock %}

orders/templates/orders/order/history.html
{% extends "food_order/base.html" %}
{% load static %}
{{ form.media }}

{% block page_header %}
  <div class="text-center"><h1>Мои заказы</h1></div>
{% endblock %}

{% block content %}
  {% if orders %}
  <div class="row mr-auto">
    <div class="col-md-1 col-lg-2"></div>
    <div class=" col-12 col-sm-12 col-md-10 col-lg-8">
      <table class="table table-striped shoplist">
        <thead class="shopunit" >
          <tr>
            <th class="primary">
              <h5 class="text-center">Номер заказа</h5>
            </th>
            <th class="primary">
              <h5 class="text-center">Дата доставки</h5>
            </th>
            <th class="primary">
              <h5 class="text-center">Сотрудник</h5>
            </th>
            <th class="primary">
              <h5 class="text-center">Состав</h5>
            </th>
            <th class="primary">
              <h5 class="text-center">Сумма</h5>
            </th>
            <th class="primary">
              <h5 class="text-center">Отчет по закзу</h5>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
            <tr>
              <td>
                <h6 class="text-center">{{ order.id }}</h6>
              </td>
              <td>
                <h6 class="text-center">{{ order.date }}</h6>
              </td>
              <td>
                <h6 class="text-center">{{ user.username }}</h6>
              </td>
              <td>
                {% for dishes in order.dishes %}
                  <h6 class="text-center">{{ dishes }}</h6>
                {% endfor %}
              </td>
              <td>
                <h6 class="text-center">{{ order.price }} ₽</h6>
              </td>
              <td>
                <a href="{% url 'orders:order_pdf' order.id %}"><h6 class="text-center"><i class="bi bi-envelope-at-fill"></i> Скачать</h6></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include "pagination.html" with page=orders %}
      <p class="text-right">
        <a  href="{% url 'food_order:dish_list' %}" class="btn btn-outline-primary">Продолжить покупки</a>
      </p>
    </div>
    <div class="col-md-1 col-lg-2"></div>
  </div>
  {% else %}
  <h4 class="mt-3 mb-3 text-center">
    Заказов еще не было
  </h4>
  {% endif %}

{% endblock %}

orders/templates/orders/order/pdf.html
<html>
<body>
  <div class="text-center"><h1>Order food</h1></div>
  <p>
    Заказ №{{ order.id }} от {{ order.created|date:"d M, Y" }}
    <br>
    Доставить {{ order.date| date:"d M, Y" }}
  </p>
  <h3>Заказчик</h3>
  <p>
    {{ order.name }}<br>
  </p>
  <h3>Товары в заказе:</h3>
  <table>
    <thead>
        <tr>
        <th>Блюдо</th>
        <th>Стоимость</th>
        <th>Количество</th>
        <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr class="row">
        <td>{{ item.dish.name }}</td>
        <td class="num">{{ item.price }} руб.</td>
        <td class="num">{{ item.quantity }}</td>
        <td class="num">{{ item.get_cost }} руб.</td>
        </tr>
        {% endfor %}
        <tr class="total">
        <td colspan="3">Итого</td>
        <td class="num">{{ order.get_total_cost }} руб.</td>
        </tr>
    </tbody>
  </table>
</body>
</html>