cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('',
         views.cart_detail,
         name='cart_detail'),
    path('add/<int:dish_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:dish_id>/',
         views.cart_remove,
         name='cart_remove'),
    path('clear/',
         views.cart_clear,
         name='cart_clear'),
    path('add_random_food/',
         views.cart_add_random_food,
         name='cart_add_random_food'),
    path('add_random_drink/',
         views.cart_add_random_drink,
         name='cart_add_random_drink'),
    path('update_plus/<int:dish_id>/',
         views.cart_update_plus,
         name='cart_update_plus'),
    path('update_minus/<int:dish_id>/',
         views.cart_update_minus,
         name='cart_update_minus'),
]

food_order/urls.py
from django.urls import path
from . import views


app_name = 'food_order'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('dishes',
         views.dish_list,
         name='dish_list'),
    path('<slug:category_slug>/',
         views.dish_list,
         name='dish_list_by_category'),
    path('<int:id>/<slug:slug>/',
         views.dish_detail,
         name='dish_detail'),
]

site_food_order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('food_order.urls', namespace='food_order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

food_order/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """ Модель категорий меню """

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food_order:dish_list_by_category',
                       args=[self.slug])


class Dish(models.Model):
    """ Модель блюда """

    category = models.ForeignKey(Category,
                                 related_name='dishes',
                                 on_delete=models.CASCADE,
                                 default=None)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50,
                            unique=True)
    image = models.ImageField(upload_to='dishes/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    composition = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food_order:dish_detail',
                       args=[self.id, self.slug])

food_order/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Dish
from cart.forms import CartAddDishForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    """Домашняя страница сервиса"""
    return render(request, 'food_order/index.html')


def dish_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    dishes_list = Dish.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        dishes_list = dishes_list.filter(category=category)
    paginator = Paginator(dishes_list, 6)
    page_number = request.GET.get('page', 1)
    try:
        dishes = paginator.page(page_number)
    except PageNotAnInteger:
        dishes = paginator.page(1)
    except EmptyPage:
        dishes = paginator.page(paginator.num_pages)
    cart_dish_form = CartAddDishForm()

    return render(request,
                  'food_order/dish/list.html',
                  {'category': category,
                   'categories': categories,
                   'dishes': dishes,
                   'cart_dish_form': cart_dish_form})


def dish_detail(request, id, slug):
    dish = get_object_or_404(Dish,
                             id=id,
                             slug=slug,
                             available=True)
    cart_dish_form = CartAddDishForm()
    return render(request,
                  'food_order/dish/detail.html',
                  {'dish': dish,
                   'cart_dish_form': cart_dish_form})

food_order/templates/food_order/dish/detail.html
{% extends "food_order/base.html" %}
{% load static %}

{% block page_header %}
  <div class="text-center"><h1>Описание</h1></div>
{% endblock %}


{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-0">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                                           src="{% if dish.image %}{{ dish.image.url }}
                                           {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="..."/></div>
                <div class="col-md-6">

                    <h2 class="display-5 fw-bolder">{{ dish.name }}</h2>
                    <p class="lead">Состав:<br>{% if dish.composition %} {{ dish.composition }} {% else %} Состав
                      отсутствует... {% endif %}</p>
                    <p class="lead">Описание:<br>{% if dish.description %} {{ dish.description }} {% else %} Описание
                        отсутствует... {% endif %}</p>
                    <div class="fs-5 mt-5 mb-3">
                        <span>Цена: {{ dish.price }} руб.</span>
                    </div>
                    <div class="fs-5 mt-1 mb-3">
                      <p><form action="{% url 'cart:cart_add' dish.id %}" method="post">
                        {{ cart_dish_form }}
                        {% csrf_token %}
                        <button role="submit" class="btn btn-primary" style="margin: 2%;">В корзину</button>
                        <input type="hidden" name="next" />
                        <a  href="{% url 'food_order:dish_list' %}" class="btn btn-outline-primary" style="width: 11rem;">Продолжить покупки</a>
                      </form></p>
                      
                  </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

food_order/templates/food_order/dish/list.html
{% extends "food_order/base.html" %}
{% load static %}

{% block page_header %}
  <div class="text-center"><h1>{% if category %}{{ category.name }}{% else %}Меню{% endif %}</h1></div>
{% endblock %}

{% block content %}
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-3 col-sm-3 col-md-2">
          <div class="list_group">
            <or {% if not category %}class="selected"{% endif %}>
              <a href="{% url 'food_order:dish_list' %}" class="list-group-item list-group-item-action">Все</a>
            </or>
            {% for c in categories %}
              <or {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}" class="list-group-item list-group-item-action">{{ c.name }}</a>
              </or>
            {% endfor %}
          </div>
          <div>
            <br>
              <form action="{% url 'cart:cart_add_random_food' %}" method="post">
                {{ cart_dish_form.override }}
                {% csrf_token %}
                <button role="submit" class="btn center btn-success">Мне повезет <br> с едой</button>
                <input type="hidden" name="next" />
              </form>
            <br>
              <form action="{% url 'cart:cart_add_random_drink' %}" method="post">
                {{ cart_dish_form.override }}
                {% csrf_token %}
                <button role="submit" class="btn btn-success">Мне повезет <br> с напитком</button>
                <input type="hidden" name="next" />
              </form>
            <br>
          </div>
        </div>
      
        

        <div class="col-8 col-sm-9 col-md-10 ">

          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li class="{{ message.tags }}">
                  {{ message|safe }}
                  <a href="#" class="close">x</a>
                </li>
              {% endfor %}
            </ul>
          {% endif %}

          <div class="row-cols-1 row-cols-sm-1 row-cols-md-2">
            <div class="card-deck mb-3 text-center">
              {% for dish in dishes %}
              <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
                <div class="card mb-4 box-shadow">
                  <div class="card-header">
                    <h4 class="my-0 font-weight-normal" style="height: 3rem">{{ dish.name }}</a></h4>
                  </div>
                    <a href="{{ dish.get_absolute_url }}">
                      <img class="card-img w-30 h-20"
                        style="height: 13rem"
                        src="{% if dish.image %}{{ dish.image.url }}
                              {% else %}{% static 'img/no_image.png' %}{% endif %}"
                        alt="">
                    </a>
                  <div class="card-body">
                    
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item card-text text-center"><h5>{{ dish.price }} руб.</h5></li>
                      <li class="list-group-item text-center">
                        <form action="{% url 'cart:cart_add' dish.id %}" method="post">
                          {{ cart_dish_form }}
                          {% csrf_token %}
                          <button role="submit" class="btn btn-primary">В корзину</button>
                          <input type="hidden" name="next" />
                        </form>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
          {% include "pagination.html" with page=dishes %}

        </div>
      </div>
    </div>
  </section>
{% endblock %}

<script src="src/bootstrap-input-spinner.js"></script>
<script>
    $("input[type='number']").inputSpinner();
</script>